### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by Raimundex** [magic7s/intelbras-solar#2]
Good morning, I did all the steps correctly, I put the intelbras folder in the custom components, I set the password, everything was fine, and I can't see anything, I looked in the log file and didn't find anything either, could you help me?

**Comment by brunopiola** [comment]
What inverter model do you have? The inverter use the app Intelbras Solar Send?

**Comment by magic7s** [comment]
EGT 4600 PROOn Nov 5, 2023, at 3:49 PM, brunopiola ***@***.***> wrote:﻿
What inverter model do you have? The inverter use the app Intelbras Solar Send?

**Comment by brunopiola** [comment]
For EGT 2000, i'm using the integration Solarman, because this integration doesn't work with microinverters.

**Comment by douglasfranciscon** [comment]
> Tenho o EGT 2000, estou usando a integração Solarman, porque essa integração não funciona com microinversores.



> I have the EGT 2000, i'm using the integration Solarman, because this integration doesn't work with microinverters.

where can I find it?

**Comment by magic7s** [comment]
> Where can I find a tutorial or instructions on how to install? I'm not sure what name the folder should have inside custom_components

The easiest way to install is to use HACS (https://www.hacs.xyz/). 
The custom_components directory is here https://github.com/magic7s/intelbras-solar/tree/main/custom_components
